language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install pytest
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - flake8
  - coverage run --source=../source -m pytest

after_success:
  - coveralls
