language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -r requirements_dev.txt

script:
  - flake8
  - coverage run --source=/source -m pytest

after_success:
  - coveralls
