language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -r requirements_dev.txt
  
before_script:
  - cd tests/
  # google chrome standalone driver
  - wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
  - unzip -y chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - sudo chmod a+x /usr/local/bin/chromedriver

script:
  - flake8
  - coverage run --source=../source -m pytest

after_success:
  - coveralls
