dist: trusty

language: python

addons:
  chrome: stable

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

script:
  - flake8
  - coverage run --source=../source -m pytest

after_success:
  - coveralls
