version: '3'
services:
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432
    networks:
      - db_network
  gentelella:
    restart: always
    env_file: .env
    build: .
    ports:
      - "5000:5000"
    networks:
      - db_network
      - web_network
    depends_on:
      - db
  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge