version: '3'
services:
  gentelella:
    restart: always
    env_file: .env
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432